### ISSUE TITLE
Fix "monthly" reoccurrence logic

### ISSUE THREAD

**Issue by lortza** [lortza/food_planner#127]
Currently the logic that determines whether a "monthly" item should be added to the grocery list any given week checks if today is the last day of the month. That means, items will only be added to the list if it is the last day of the month _and_ a tuesday -- which is the day of the week that the task runs.

**Comment by mikevallano** [comment]
Off the top, something like this should work:

```ruby
 Date.current.month == 1.week.from_now.month
```

`month` returns an integer (10 for October, for example).

So if one week from now is a different month, then today must be the last [day of the week] of the month. I think. 🤷‍♂

**Comment by lortza** [comment]
I like it!
